apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
  labels:
    app: argo-rollouts
spec:
  project: default

  source:
    repoURL: 'https://github.com/argoproj/argo-helm'
    chart: argo-rollouts
    targetRevision: 2.37.7

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-rollouts

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
