apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mamaloo-prod
  namespace: argocd
  labels:
    app: mamaloo
    environment: prod
spec:
  project: default
  
  source:
    repoURL: 'https://github.com/Analarie/Portal-Mamaloo-desenvolvimento.git'
    targetRevision: main
    path: helm/mamaloo-app
    helm:
      valueFiles:
        - values-prod.yaml
  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mamaloo-prod
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
