apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mamaloo-dev
  namespace: argocd
  labels:
    app: mamaloo
    environment: dev
spec:
  project: default
  
  source:
    repoURL: 'https://github.com/Analarie/Portal-Mamaloo-desenvolvimento.git'
    targetRevision: desenvolvimento
    path: helm/mamaloo-app
    helm:
      valueFiles:
        - values-dev.yaml
  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mamaloo-dev
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
